### ISSUE TITLE
Renaming from Example to "whatever" results in Error

### ISSUE THREAD

**Issue by ribase** [FluidTYPO3/builder#100]
When you rename ../Private/Templates/Content/Example.html into something else, it returns a FE error and the backendfields are missing.

Is this a bug? Nothing found to set a template name.

**Comment by NamelessCoder** [comment]
I'm a bit sorry to say that this is expected behavior, but it has a very good reason. We can't monitor template files to detect changes and then modify the database to update this - such a thing should not be done unless you are in development and in development you can fix this quite easily. The files should be considered permanent fixtures and you need to take care that each version you produce is compatible with the ones you previously produced, if compatibility is required.

If you do need to do this in production some day, you can always move the essential rendering to a Partial and rather than *rename* the file, *duplicate* it but set `enabled="0"` on the old version, then render both of them via the Partial. That means that the old version can no longer be selected but will still be able to be rendered by the frontend controller (until such a time that you either use an SQL query or manual content editing to change usages of the old template to use the new).

**Comment by NamelessCoder** [comment]
PS: this is of course only an issue if you have existing content elements or pages referencing the template because the name gets saved in the records in DB. If you don't have any instances of the templates being used then files can be freely renamed and after clearing caches the system should just start using the renamed file instead.

**Comment by ribase** [comment]
Thx!
