### ISSUE TITLE
Future of builder

### ISSUE THREAD

**Issue by daCyberpunk** [FluidTYPO3/builder#120]
Hi!
Even the last commit is roughly two years old I need to ask: Is there a future for this extension? 
Today I searched for it because I want to scan the fluid templates on a project, and realized that either you nor others are offering this anymore. Thats a pity! 

Just asking :-)

**Comment by NamelessCoder** [comment]
Hi Falk,

EXT:builder follows Flux and usually gets updated around major releases (the only time there's a need, possibly, to update the templates or metadata files it generates). That's why there has been no updates since around the time of the last Flux major version.

This time it should be a fairly simple matter of updating the metadata files to remove `fluidcontent` as dependency, perhaps adjust a couple of template files, and use a different parent class name for the ContentController if one is generated. A `ContentController` class exists in Flux with the exact same class name and path, just `Flux` as namespace segment instead of `Fluidcontent`.

And both I and users would appreciate if you would give a try at making a pull request that changes these things! ;) because we do need a new release of EXT:builder that generates for Flux 9.x and is compatible with TYPO3 8.7 / 9.x.

**Comment by ZweisteinT** [comment]
Hi, im new to this and found my way here through a tutorial.
Does it mean its not possible to use typo3 9.x with fluid 9.x?

**Comment by ZweisteinT** [comment]
I saw you updates the files here more recently than then Version i found using the typo3 Extension installer.
Sadly after uploading your source manually into Extension Manager i got the error:

"Oops, an error occurred!
Call to a member function getPackagePath() on null "

After that my whole typo3 9.5.1 Installation stopped working :) Just shows "Oops, an error occurred!". Error may or may not have anything to do with your Code.

**Comment by NamelessCoder** [comment]
Make sure you (manually, sometimes required) flush all cache files that contain generated code or class reflections. Enabling development context and debug mode also helps produce more appropriate errors. But in your case it's almost surely a matter of cached class reflections that for example caused a dependency instance to not be injected correctly.

**Comment by ZweisteinT** [comment]
After reinstalling 9.5.1, and installing the extensions flux, vhs and fluidpages (all GitHub versions), i could install the builder as well (also GitHub version). Works, just that error with required "Vendor.key" Format for all fields including the mailadress (see alexanders issue) is strange.

When i used all "official" versions, the builder didnt appear in the typo3 menu on the left side (under admin panel). But GitHub Versions worked.

**Comment by X-Tender** [comment]
@ZweisteinT Did you used the development branch or the master branch? I Downloaded the dev branches of flux,vhx,fluidpages and builder and get the error:
`Class 'FluidTYPO3\Fluidpages\Controller\PageControllerInterface' not found`

**Comment by ghwaldo** [comment]
Ist this working for TYPO3 10.4 if i edit ext_emconf.php ? Any experiences ?

**Comment by NamelessCoder** [comment]
No, EXT:builder is currently not working with TYPO3v10 versions.

**Comment by NamelessCoder** [comment]
Extension updated to support TYPO3 10.4. If you wouldn't mind, please test the `development` branch and let me know if you run into any problems.
